=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Ejemplo 4/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="listaclientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string"></xs:element>

                            <xs:choice>
                                <xs:element name="dni" type="tipodni" />
                                <xs:element name="nie" type="xs:string"></xs:element>
                            </xs:choice>

                            <xs:element name="compras" type="tipocompra"></xs:element>
                            <xs:element name="regalo" type="xs:string" minOccurs="0"
                                maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="español" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- TIPOS PERSONALIZADOS-->
    <!-- Logitud DNI-->
    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:maxLength value="9"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <!-- Compra -->
    <xs:simpleType name="tipocompra">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="3000"></xs:minExclusive>
            <xs:maxExclusive value="5000"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoespañol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="si"></xs:enumeration>
            <xs:enumeration value="SI"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
            <xs:enumeration value="NO"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Ejemplo 4/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaclientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientes.xsd">

    <cliente español="si">
        <nombre>Juan</nombre>
        <apellido>Sanchez</apellido>
        <dni>33158697A</dni>
        <compras>4800</compras>
        <regalo>bolsa deporte</regalo>
    </cliente>

    <cliente español="no">
        <nombre>Jose</nombre>
        <apellido>Diaz</apellido>
        <nie>67388382T</nie>
        <compras>4500</compras>
    </cliente>

</listaclientes>
