=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Ejemplo 3/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>

                            <xs:choice>
                                <xs:element name="cilindrada" type="xs:float" minOccurs="0"></xs:element>
                                <xs:element name="caballos" type="xs:float" minOccurs="0"></xs:element>
                            </xs:choice>

                            <xs:element name="combustible" type="xs:string"></xs:element>
                            <xs:element name="precio" type="xs:string"></xs:element>
                            <xs:element name="año" type="xs:unsignedShort" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="xs:string" minOccurs="0"
                                maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Ejemplo 3/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">

    <coche matricula="8280DGH">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000</precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33358697A</interesado>
        <interesado>30515455T</interesado>
    </coche>

    <coche matricula="8280DGH">
        <marca>Volkswangen</marca>
        <modelo>Polo</modelo>
        <cilindrada>1.2</cilindrada>
        <combustible>Gasolina</combustible>
        <precio>5.000</precio>
        <color>rojo</color>
        <interesado>60514553T</interesado>
    </coche>

    <coche matricula="8280DGH">
        <marca>Renault</marca>
        <modelo>Megane</modelo>
        <caballos>1.2</caballos>
        <combustible>Diesel</combustible>
        <precio>7.500</precio>
        <color>verde</color>
    </coche>

</concesionario>
