=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Prueba Practica/Práctica_evaluable_ZairDeLaCruz_Tema11/componentes.xsd
<?xml version="1.0" encoding=""?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="listacomponentes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="componente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            <xs:element name="categoria" type="tipocategoria"></xs:element>
                            <xs:element name="precio" type="tipocompra"></xs:element>

                            <xs:choice>
                                <xs:element name="stock" type="xs:unsignedShort" minOccurs="0"></xs:element> <!--
                                Opcional-->
                                <xs:element name="cantidad" type="xs:unsignedShort" minOccurs="0"></xs:element> <!--
                                Opcional-->
                            </xs:choice>

                            <xs:element name="fecha_alta" type="xs:date"></xs:element>
                            <xs:element name="garantia" type="tipogarantia" minOccurs="0"></xs:element> <!--
                            Opcional-->
                            <xs:element name="color" type="xs:string" minOccurs="0"></xs:element> <!--
                            Opcional-->
                            <xs:element name="cliente_reserva" type="tipodni" minOccurs="0"
                                maxOccurs="2"></xs:element> <!-- Opcional-->
                            <xs:element name="extras" type="xs:string" minOccurs="0" maxOccurs="2"></xs:element> <!--
                            Opcional-->

                        </xs:sequence>
                        <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipocategoria">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CPU"></xs:enumeration>
            <xs:enumeration value="GPU"></xs:enumeration>
            <xs:enumeration value="RAM"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocompra">
        <xs:restriction base="xs:double">
            <xs:minExclusive value="1"></xs:minExclusive>
            <xs:maxExclusive value="300"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipogarantia">
        <xs:restriction base="xs:int">
            <xs:minExclusive value="6"></xs:minExclusive>
            <xs:maxExclusive value="60"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== zdm67/1DAM_LMSGI_ZDM/TEMA 11/Prueba Practica/Práctica_evaluable_ZairDeLaCruz_Tema11/componentes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<listacomponentes
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="componentes.xsd">

  <componente tipo="CPU">
    <marca>Intel</marca>
    <modelo>i5-12400F</modelo>
    <categoria>CPU</categoria>
    <precio>180</precio>
    <stock>12</stock>
    <fecha_alta>2025-10-05</fecha_alta>
    <garantia>24</garantia>
    <color>Negro</color>
    <cliente_reserva>12345678Z</cliente_reserva>
    <cliente_reserva>87654321H</cliente_reserva>
    <extras>Disipador PastaTermica</extras>
  </componente>

  <componente tipo="GPU">
    <marca>NVIDIA</marca>
    <modelo>RTX4060</modelo>
    <categoria>GPU</categoria>
    <precio>299.99</precio>
    <cantidad>3</cantidad>
    <fecha_alta>2025-11-20</fecha_alta>
    <garantia>36</garantia>
    <extras>Backplate Manual</extras>
  </componente>

  <componente tipo="RAM">
    <marca>Corsair</marca>
    <modelo>Vengeance16GB</modelo>
    <categoria>RAM</categoria>
    <precio>75</precio>
    <fecha_alta>2025-09-12</fecha_alta>
    <color>Blanco</color>
  </componente>
</listacomponentes>
